server.port=8080

spring.jpa.database=POSTGRESQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=false

# Mejor que create-drop en prod
spring.jpa.hibernate.ddl-auto=update 

# Configuraciones de seguridad y performance
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# Data initialization
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:/dataTest.sql